# Generated by Django 3.1.4 on 2022-10-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='usuario',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
